---
#
# PLEASE NOTE: Managed workflow - do not change manually
#
name: Publish

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

concurrency:
  # only run one publishing at a time to avoid conflicts
  group: publish-${{ github.ref }}

jobs:
  publish:
    uses: wetransform/gha-workflows/.github/workflows/gradle-library-publish.yml@68d112116f95cc21ee4a09c974e7c2fcfba46c19 # v2.0.4
    with:
      expect-tests: false
      java-version: 17
      multi-module: true
      semantic-release: false
    secrets:
      WETF_ARTIFACTORY_USER: ${{ secrets.WETF_ARTIFACTORY_USER }}
      WETF_ARTIFACTORY_PASSWORD: ${{ secrets.WETF_ARTIFACTORY_PASSWORD }}
      SLACK_NOTIFICATIONS_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
