---
#
# PLEASE NOTE: Managed workflow - do not change manually
#
name: Release

on:
  workflow_dispatch: {}

concurrency:
  # only run one publishing at a time to avoid conflicts
  group: publish-${{ github.ref }}

jobs:
  publish:
    uses: wetransform/gha-workflows/.github/workflows/gradle-library-publish.yml@b8c60e9a57fb6e01bf675dae1bb7fd14cbc1f399 # v2.0.2
    with:
      expect-tests: false
      java-version: 17
      multi-module: true
      semantic-release: true
    secrets:
      WETF_ARTIFACTORY_USER: ${{ secrets.WETF_ARTIFACTORY_USER }}
      WETF_ARTIFACTORY_PASSWORD: ${{ secrets.WETF_ARTIFACTORY_PASSWORD }}
      SLACK_NOTIFICATIONS_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      WE_RELEASE_GITHUB_APP_ID: ${{ secrets.WE_RELEASE_GITHUB_APP_ID }}
      WE_RELEASE_GITHUB_PRIVATE_KEY: ${{ secrets.WE_RELEASE_GITHUB_PRIVATE_KEY }}
